// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNIq27OOR65ua8by_xCWYLe5_TiBalY54',
    appId: '1:97169397136:web:6ee85087cff7ef53e24f15',
    messagingSenderId: '97169397136',
    projectId: 'ynot-ea26e',
    authDomain: 'ynot-ea26e.firebaseapp.com',
    storageBucket: 'ynot-ea26e.appspot.com',
    measurementId: 'G-WMF18ZJVV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNLJYGjX0CRTT4FA_TKckLuVAxSPFXoao',
    appId: '1:97169397136:android:fbb3ac1541adf135e24f15',
    messagingSenderId: '97169397136',
    projectId: 'ynot-ea26e',
    storageBucket: 'ynot-ea26e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVPmsxaOmz6qamNJfwQrOJ7cZvtawULiQ',
    appId: '1:97169397136:ios:e1820cf27965d34ce24f15',
    messagingSenderId: '97169397136',
    projectId: 'ynot-ea26e',
    storageBucket: 'ynot-ea26e.appspot.com',
    iosBundleId: 'com.example.todoAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVPmsxaOmz6qamNJfwQrOJ7cZvtawULiQ',
    appId: '1:97169397136:ios:17a3e17d299b6ceae24f15',
    messagingSenderId: '97169397136',
    projectId: 'ynot-ea26e',
    storageBucket: 'ynot-ea26e.appspot.com',
    iosBundleId: 'com.example.todoAppFirebase.RunnerTests',
  );
}
